### ISSUE TITLE
Problems when running MWE2 with exec-maven-plugin due to non consistent EMF dependencies

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-xtext/xtext#3304]
In my DSL https://github.com/LorenzoBettini/edelta when switching to Xtext 2.37.0 and 2024-12, the MWE2 workflow executed through exec-maven-plugin I get this failure:

```
2178 [org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main()] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - 'java.net.URL org.eclipse.emf.common.util.CommonUtil.newURL(java.lang.String)'
java.lang.NoSuchMethodError: 'java.net.URL org.eclipse.emf.common.util.CommonUtil.newURL(java.lang.String)'
	at org.eclipse.emf.codegen.jet.JETCompiler.openStream(JETCompiler.java:1442)
	at org.eclipse.emf.codegen.jet.JETCompiler.findLocation(JETCompiler.java:1372)
	at org.eclipse.emf.codegen.jet.JETCompiler.findLocation(JETCompiler.java:1348)
	at org.eclipse.emf.codegen.jet.JETCompiler.find(JETCompiler.java:1417)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.getMergeRulesURI(GenModelGeneratorAdapterFactory.java:263)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.initializeMergeRulesURI(GenModelGeneratorAdapterFactory.java:195)
	at org.eclipse.emf.codegen.ecore.genmodel.generator.GenModelGeneratorAdapterFactory.initialize(GenModelGeneratorAdapterFactory.java:168)
	at org.eclipse.emf.codegen.ecore.generator.Generator.initialize(Generator.java:285)
	at org.eclipse.emf.codegen.ecore.generator.Generator.setInput(Generator.java:254)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.doGenerate(EMFGeneratorFragment2.java:1021)
	at org.eclipse.xtext.xtext.generator.ecore.EMFGeneratorFragment2.generate(EMFGeneratorFragment2.java:476)
	at org.eclipse.xtext.xtext.generator.CompositeGeneratorFragment2.generate(CompositeGeneratorFragment2.java:43)
	at org.eclipse.xtext.xtext.generator.XtextGenerator.invokeInternal(XtextGenerator.java:228)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:133)
	at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:35)
	at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(AbstractWorkflowComponent.java:213)
	at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.invoke(AbstractCompositeWorkflowComponent.java:38)
	at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:21)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:103)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
	at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
	at org.codehaus.mojo.exec.ExecJavaMojo.doMain(ExecJavaMojo.java:385)
	at org.codehaus.mojo.exec.ExecJavaMojo.doExec(ExecJavaMojo.java:374)
	at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0(ExecJavaMojo.java:296)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

I still have to check whether using the new generator.dependencies bundle triggers the problem.

The root cause is that the `JETCompiler` uses a new method `org.eclipse.emf.common.util.CommonUtil.newURL(java.lang.String)`, introduced in emf.common in 2.40, while our pinned version is 2.24.0. I guess that `emf.codegen` is a newer version, while `emf.common` is an old one...

I'll inspect further and see whether the generator.dependencies has to be updated accordingly.

**Comment by LorenzoBettini** [comment]
I found the problem, its source and the solution. I'm using Xtext 2.37.0 so the dependency versions are older than the current Xtext, but the problem is the same.

As I said, the problem is that `emf.codegen` is used in its newer version, and it uses a new API in `emf.common` introduced in the latest version, but during the `exec-maven-plugin` run, the old `emf.common` is used, and so we get the exception.

In particular, this Maven version is used `org.eclipse.emf:org.eclipse.emf.common:jar:2.24.0:compile`.

The problem happens in my DSL but not in other Xtext examples because my DSL project's POM specifies some Maven dependencies since it is meant to be used also as a Maven artifact. Basically, the same approach of Xtext bundles that are meant to be used as Maven dependencies.

In particular, my DSL POM has as a Maven dependency:

```xml
      <dependency>
        <groupId>org.eclipse.xtext</groupId>
        <artifactId>org.eclipse.xtext.ecore</artifactId>
        <version>${xtextVersion}</version>
      </dependency>
```

That has a (correctly) pinned dependency on `emf.common`.

Looking at the dependency tree:

```
[INFO] +- org.eclipse.xtext:org.eclipse.xtext.ecore:jar:2.37.0:compile
[INFO] |  \- org.eclipse.xtext:org.eclipse.xtext:jar:2.37.0:compile
[INFO] |     +- org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.37.0:compile
[INFO] |     |  \- org.eclipse.xtend:org.eclipse.xtend.lib.macro:jar:2.37.0:compile
[INFO] |     +- org.eclipse.xtext:org.eclipse.xtext.util:jar:2.37.0:compile
[INFO] |     +- org.eclipse.platform:org.eclipse.equinox.common:jar:3.17.100:compile
[INFO] |     +- org.eclipse.platform:org.eclipse.osgi:jar:3.18.300:compile
[INFO] |     +- org.eclipse.emf:org.eclipse.emf.common:jar:2.24.0:compile
[INFO] |     \- org.antlr:antlr-runtime:jar:3.2:compile
```

And here's how the old version of `emf.common` is used.

I think this is the root of the problems I experienced in the past in my DSL.

The solution is to use the new `xtext.generator.dependencies` as a dependency of the `exec-maven-plugin`.

```xml
	<includePluginDependencies>true</includePluginDependencies>
</configuration>
<dependencies>
	<dependency>
		<groupId>org.eclipse.xtext</groupId>
		<artifactId>org.eclipse.xtext.xtext.generator.dependencies</artifactId>
		<version>${xtext-version}</version>
	</dependency>
</dependencies>
```

This way, when the `exec-maven-plugin` is executed it will NOT use the newer version of `emf.codegen`!

This problem can be reproduced also in an Xtext project, based on Maven/Tycho generated by our wizard.

To see the problem in action, in the DSL POM add this (the version is taken from our BOM):

```xml
	<artifactId>org.xtext.example.mydsl</artifactId>
	<packaging>eclipse-plugin</packaging>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
		</dependency>
	</dependencies>
```

Run the Maven build and see the exception when it gets to `exec-maven-plugin`.

To solve, add the

```xml
<artifactId>org.eclipse.xtext.xtext.generator.dependencies</artifactId>
```

as above, and the problem goes away.

I'd suggest to change our wizard so that it generates:

```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>exec-maven-plugin</artifactId>
	<version>3.0.0</version>
	<executions>
		<execution>
			<?m2e ignore?>
			<id>mwe2Launcher</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>java</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<mainClass>org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher</mainClass>
...
		<classpathScope>compile</classpathScope>
		<includePluginDependencies>true</includePluginDependencies>
		<cleanupDaemonThreads>false</cleanupDaemonThreads><!-- see https://bugs.eclipse.org/bugs/show_bug.cgi?id=475098#c3 -->
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.xtext.generator.dependencies</artifactId>
			<version>${xtextVersion}</version>
		</dependency>
	</dependencies>
</plugin>
```

Note that the antlr-generator is now a dependency of xtext.generator.dependencies so we don't have to add it anymore if we add xtext.generator.dependencies.

@cdietrich how does it sound?

**Comment by LorenzoBettini** [comment]
> Can you provide sample prs on xtext-reference projects

Do you mean modify one of the reference projects?

By the way, with a fresh project created with the wizard the exception is slightly different:

```
Caused by: java.lang.NoSuchMethodError: 'java.net.URL org.eclipse.emf.common.util.CommonUtil.newURL(java.lang.String)'
	at org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createInputStream(URIHandlerImpl.java:199)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
	at org.eclipse.xtext.resource.XtextResourceSet$1.createInputStream(XtextResourceSet.java:299)
	at org.eclipse.xtext.common.types.access.impl.ClasspathTypeProvider$JavaURIConverter.createInputStream(ClasspathTypeProvider.java:89)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1314)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:33)
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadResource(BaseEPackageAccess.java:53)
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadGrammarFile(BaseEPackageAccess.java:45)
	at org.eclipse.xtext.service.GrammarProvider.doGetGrammar(GrammarProvider.java:71)
	at org.eclipse.xtext.service.GrammarProvider.getGrammar(GrammarProvider.java:53)
	at org.eclipse.emf.mwe2.language.services.Mwe2GrammarAccess.internalFindGrammar(Mwe2GrammarAccess.java:945)
	at org.eclipse.emf.mwe2.language.services.Mwe2GrammarAccess.<init>(Mwe2GrammarAccess.java:914)
```

but the problem is the same.

**Comment by cdietrich** [comment]
I mean you change the wizard created example s and the domain model example how they would look like after your change to the wizard
